// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1623926203;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__instance__acquire_instance_slot_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "acquire_instance_slot",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_max_slots = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::instance::acquire_instance_slot(api_max_slots))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__advancement_option_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "advancement_option",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_character = <crate::api::engine::CharacterDto>::sse_decode(&mut deserializer);
            let api_settings = <crate::api::engine::RoomSettingsDto>::sse_decode(&mut deserializer);
            let api_player_dice = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_opposition_dice = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_skill_index = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                let output_ok = crate::api::engine::advancement_option(
                    api_character,
                    api_settings,
                    api_player_dice,
                    api_opposition_dice,
                    api_skill_index,
                )?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__flow__allowed_roll_actions_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "allowed_roll_actions",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_state = <crate::api::flow::RollStateDto>::sse_decode(&mut deserializer);
            let api_advance = <Option<crate::api::flow::AdvanceStateDto>>::sse_decode(&mut deserializer);
            let api_actor = <crate::api::flow::ActorDto>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::flow::allowed_roll_actions(
                    api_state,
                    api_advance,
                    api_actor,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__apply_roll_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "apply_roll",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_character = <crate::api::engine::CharacterDto>::sse_decode(&mut deserializer);
            let api_settings = <crate::api::engine::RoomSettingsDto>::sse_decode(&mut deserializer);
            let api_player_dice = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_opposition_dice = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_skill_index = <u32>::sse_decode(&mut deserializer);
            let api_choice = <Option<crate::api::engine::AdvancementChoiceDto>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                let output_ok = crate::api::engine::apply_roll(
                    api_character,
                    api_settings,
                    api_player_dice,
                    api_opposition_dice,
                    api_skill_index,
                    api_choice,
                )?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__flow__declare_roll_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "declare_roll",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_action = <String>::sse_decode(&mut deserializer);
            let api_skill = <crate::api::flow::SkillRefDto>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                let output_ok = crate::api::flow::declare_roll(api_action, api_skill)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__default_room_settings_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "default_room_settings",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::engine::default_room_settings())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::engine::init_app();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__engine__new_character_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "new_character",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_description = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                let output_ok = crate::api::engine::new_character(api_name, api_description)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__flow__parse_roll_state_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "parse_roll_state",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::flow::parse_roll_state(api_id))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__resolve_roll_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "resolve_roll",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_player_dice = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_opposition_dice = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_settings = <crate::api::engine::RoomSettingsDto>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                let output_ok = crate::api::engine::resolve_roll(api_player_dice, api_opposition_dice, api_settings)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__roll_dice_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "roll_dice",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_count = <u8>::sse_decode(&mut deserializer);
            let api_max_dice = <u8>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                let output_ok = crate::api::engine::roll_dice(api_count, api_max_dice)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__flow__roll_state_id_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "roll_state_id",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_state = <crate::api::flow::RollStateDto>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::flow::roll_state_id(api_state))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__flow__roll_transition_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "roll_transition",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_record = <crate::api::flow::RollRecordDto>::sse_decode(&mut deserializer);
            let api_action = <crate::api::flow::FlowActionDto>::sse_decode(&mut deserializer);
            let api_actor = <crate::api::flow::ActorDto>::sse_decode(&mut deserializer);
            let api_max_dice = <u8>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                let output_ok = crate::api::flow::roll_transition(api_record, api_action, api_actor, api_max_dice)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__slot_usage_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "slot_usage",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_character = <crate::api::engine::CharacterDto>::sse_decode(&mut deserializer);
            let api_settings = <crate::api::engine::RoomSettingsDto>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::engine::slot_usage(api_character, api_settings))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__validate_character_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "validate_character",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_character = <crate::api::engine::CharacterDto>::sse_decode(&mut deserializer);
            let api_settings = <crate::api::engine::RoomSettingsDto>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::engine::validate_character(api_character, api_settings))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__validate_item_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "validate_item",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_item = <crate::api::engine::ItemDto>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::engine::validate_item(api_item))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine__validate_room_settings_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "validate_room_settings",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_)
            };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_settings = <crate::api::engine::RoomSettingsDto>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::engine::validate_room_settings(api_settings))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::flow::ActorDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::flow::ActorDto::Dm,
            1 => crate::api::flow::ActorDto::Owner,
            2 => crate::api::flow::ActorDto::Other,
            _ => unreachable!("Invalid variant for ActorDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::flow::AdvanceStateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::flow::AdvanceStateDto::Pendiente,
            1 => crate::api::flow::AdvanceStateDto::Aplicado,
            2 => crate::api::flow::AdvanceStateDto::NoAplica,
            _ => unreachable!("Invalid variant for AdvanceStateDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::engine::AdvancementChoiceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_newSkillName = <String>::sse_decode(deserializer);
        let mut var_slot = <crate::api::engine::SlotChoiceKind>::sse_decode(deserializer);
        let mut var_replaceIndex = <u32>::sse_decode(deserializer);
        return crate::api::engine::AdvancementChoiceDto {
            new_skill_name: var_newSkillName,
            slot: var_slot,
            replace_index: var_replaceIndex,
        };
    }
}

impl SseDecode for crate::api::engine::AdvancementOptionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sourceSkillIndex = <u32>::sse_decode(deserializer);
        let mut var_sourceLabel = <String>::sse_decode(deserializer);
        let mut var_newLevel = <u8>::sse_decode(deserializer);
        let mut var_natural = <bool>::sse_decode(deserializer);
        let mut var_xpCost = <u32>::sse_decode(deserializer);
        let mut var_xpAvailable = <u32>::sse_decode(deserializer);
        let mut var_slotsFull = <bool>::sse_decode(deserializer);
        return crate::api::engine::AdvancementOptionDto {
            source_skill_index: var_sourceSkillIndex,
            source_label: var_sourceLabel,
            new_level: var_newLevel,
            natural: var_natural,
            xp_cost: var_xpCost,
            xp_available: var_xpAvailable,
            slots_full: var_slotsFull,
        };
    }
}

impl SseDecode for crate::api::flow::AppliedAdvanceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_xpGained = <u32>::sse_decode(deserializer);
        let mut var_xpSpent = <u32>::sse_decode(deserializer);
        let mut var_newSkill = <Option<crate::api::engine::SkillDto>>::sse_decode(deserializer);
        let mut var_replacedIndex = <Option<u32>>::sse_decode(deserializer);
        return crate::api::flow::AppliedAdvanceDto {
            xp_gained: var_xpGained,
            xp_spent: var_xpSpent,
            new_skill: var_newSkill,
            replaced_index: var_replacedIndex,
        };
    }
}

impl SseDecode for crate::api::engine::ApplyResultDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_character = <crate::api::engine::CharacterDto>::sse_decode(deserializer);
        let mut var_xpGained = <u32>::sse_decode(deserializer);
        let mut var_xpSpent = <u32>::sse_decode(deserializer);
        let mut var_newSkill = <Option<crate::api::engine::SkillDto>>::sse_decode(deserializer);
        let mut var_replacedIndex = <Option<u32>>::sse_decode(deserializer);
        let mut var_replacedSkill = <Option<crate::api::engine::SkillDto>>::sse_decode(deserializer);
        return crate::api::engine::ApplyResultDto {
            character: var_character,
            xp_gained: var_xpGained,
            xp_spent: var_xpSpent,
            new_skill: var_newSkill,
            replaced_index: var_replacedIndex,
            replaced_skill: var_replacedSkill,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::engine::CharacterDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_description = <String>::sse_decode(deserializer);
        let mut var_notes = <String>::sse_decode(deserializer);
        let mut var_xp = <u32>::sse_decode(deserializer);
        let mut var_skills = <Vec<crate::api::engine::SkillDto>>::sse_decode(deserializer);
        return crate::api::engine::CharacterDto {
            name: var_name,
            description: var_description,
            notes: var_notes,
            xp: var_xp,
            skills: var_skills,
        };
    }
}

impl SseDecode for crate::api::flow::FlowActionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::flow::FlowActionKindDto>::sse_decode(deserializer);
        let mut var_skill = <Option<crate::api::flow::SkillRefDto>>::sse_decode(deserializer);
        let mut var_text = <Option<String>>::sse_decode(deserializer);
        let mut var_dice = <Option<Vec<u8>>>::sse_decode(deserializer);
        let mut var_tieWinner = <Option<crate::api::engine::TieWinnerDto>>::sse_decode(deserializer);
        let mut var_applied = <Option<crate::api::flow::AppliedAdvanceDto>>::sse_decode(deserializer);
        return crate::api::flow::FlowActionDto {
            kind: var_kind,
            skill: var_skill,
            text: var_text,
            dice: var_dice,
            tie_winner: var_tieWinner,
            applied: var_applied,
        };
    }
}

impl SseDecode for crate::api::flow::FlowActionKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::flow::FlowActionKindDto::Approve,
            1 => crate::api::flow::FlowActionKindDto::CounterOffer,
            2 => crate::api::flow::FlowActionKindDto::Reject,
            3 => crate::api::flow::FlowActionKindDto::Narrate,
            4 => crate::api::flow::FlowActionKindDto::AcceptCounterOffer,
            5 => crate::api::flow::FlowActionKindDto::Redeclare,
            6 => crate::api::flow::FlowActionKindDto::Withdraw,
            7 => crate::api::flow::FlowActionKindDto::RollOpposition,
            8 => crate::api::flow::FlowActionKindDto::RollPlayer,
            9 => crate::api::flow::FlowActionKindDto::Resolve,
            10 => crate::api::flow::FlowActionKindDto::ApplyAdvance,
            _ => unreachable!("Invalid variant for FlowActionKindDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::flow::HistoryEntryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_from = <Option<crate::api::flow::RollStateDto>>::sse_decode(deserializer);
        let mut var_to = <crate::api::flow::RollStateDto>::sse_decode(deserializer);
        let mut var_by = <crate::api::flow::ActorDto>::sse_decode(deserializer);
        return crate::api::flow::HistoryEntryDto {
            from: var_from,
            to: var_to,
            by: var_by,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::engine::ItemDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_description = <String>::sse_decode(deserializer);
        let mut var_value = <Option<u32>>::sse_decode(deserializer);
        let mut var_quantity = <u32>::sse_decode(deserializer);
        return crate::api::engine::ItemDto {
            name: var_name,
            description: var_description,
            value: var_value,
            quantity: var_quantity,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::flow::FlowActionKindDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::flow::FlowActionKindDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::flow::HistoryEntryDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::flow::HistoryEntryDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::engine::SkillDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::engine::SkillDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::flow::AdvanceStateDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::flow::AdvanceStateDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::engine::AdvancementChoiceDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::engine::AdvancementChoiceDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::engine::AdvancementOptionDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::engine::AdvancementOptionDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::flow::AppliedAdvanceDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::flow::AppliedAdvanceDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::flow::RollResultDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::flow::RollResultDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::flow::RollStateDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::flow::RollStateDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::engine::SkillDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::engine::SkillDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::flow::SkillRefDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::flow::SkillRefDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::engine::TieWinnerDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::engine::TieWinnerDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<u8>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::engine::RollOutcomeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_playerTotal = <u32>::sse_decode(deserializer);
        let mut var_oppositionTotal = <u32>::sse_decode(deserializer);
        let mut var_xpGained = <u32>::sse_decode(deserializer);
        return crate::api::engine::RollOutcomeDto {
            success: var_success,
            player_total: var_playerTotal,
            opposition_total: var_oppositionTotal,
            xp_gained: var_xpGained,
        };
    }
}

impl SseDecode for crate::api::flow::RollRecordDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_state = <crate::api::flow::RollStateDto>::sse_decode(deserializer);
        let mut var_action = <String>::sse_decode(deserializer);
        let mut var_skill = <crate::api::flow::SkillRefDto>::sse_decode(deserializer);
        let mut var_counterOffer = <Option<crate::api::flow::SkillRefDto>>::sse_decode(deserializer);
        let mut var_dmNote = <Option<String>>::sse_decode(deserializer);
        let mut var_opposition = <Option<Vec<u8>>>::sse_decode(deserializer);
        let mut var_playerRoll = <Option<Vec<u8>>>::sse_decode(deserializer);
        let mut var_result = <Option<crate::api::flow::RollResultDto>>::sse_decode(deserializer);
        let mut var_narration = <Option<String>>::sse_decode(deserializer);
        let mut var_tieWinner = <Option<crate::api::engine::TieWinnerDto>>::sse_decode(deserializer);
        let mut var_advance = <Option<crate::api::flow::AdvanceStateDto>>::sse_decode(deserializer);
        let mut var_applied = <Option<crate::api::flow::AppliedAdvanceDto>>::sse_decode(deserializer);
        let mut var_history = <Vec<crate::api::flow::HistoryEntryDto>>::sse_decode(deserializer);
        return crate::api::flow::RollRecordDto {
            state: var_state,
            action: var_action,
            skill: var_skill,
            counter_offer: var_counterOffer,
            dm_note: var_dmNote,
            opposition: var_opposition,
            player_roll: var_playerRoll,
            result: var_result,
            narration: var_narration,
            tie_winner: var_tieWinner,
            advance: var_advance,
            applied: var_applied,
            history: var_history,
        };
    }
}

impl SseDecode for crate::api::flow::RollResultDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::flow::RollResultDto::Exito,
            1 => crate::api::flow::RollResultDto::Fallo,
            2 => crate::api::flow::RollResultDto::Narrado,
            _ => unreachable!("Invalid variant for RollResultDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::flow::RollStateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::flow::RollStateDto::Declarada,
            1 => crate::api::flow::RollStateDto::Aprobada,
            2 => crate::api::flow::RollStateDto::Contraoferta,
            3 => crate::api::flow::RollStateDto::Rechazada,
            4 => crate::api::flow::RollStateDto::SinTirada,
            5 => crate::api::flow::RollStateDto::Oposicion,
            6 => crate::api::flow::RollStateDto::Tirada,
            7 => crate::api::flow::RollStateDto::Resuelta,
            8 => crate::api::flow::RollStateDto::Retirada,
            _ => unreachable!("Invalid variant for RollStateDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::engine::RoomSettingsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_skillSlots = <u8>::sse_decode(deserializer);
        let mut var_tieWinner = <crate::api::engine::TieWinnerDto>::sse_decode(deserializer);
        let mut var_xpSameRoll = <bool>::sse_decode(deserializer);
        let mut var_maxDice = <u8>::sse_decode(deserializer);
        return crate::api::engine::RoomSettingsDto {
            skill_slots: var_skillSlots,
            tie_winner: var_tieWinner,
            xp_same_roll: var_xpSameRoll,
            max_dice: var_maxDice,
        };
    }
}

impl SseDecode for crate::api::engine::SkillDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_level = <u8>::sse_decode(deserializer);
        let mut var_permanent = <bool>::sse_decode(deserializer);
        let mut var_derivedFrom = <Option<String>>::sse_decode(deserializer);
        return crate::api::engine::SkillDto {
            name: var_name,
            level: var_level,
            permanent: var_permanent,
            derived_from: var_derivedFrom,
        };
    }
}

impl SseDecode for crate::api::flow::SkillRefDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_index = <u32>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_level = <u8>::sse_decode(deserializer);
        return crate::api::flow::SkillRefDto {
            index: var_index,
            name: var_name,
            level: var_level,
        };
    }
}

impl SseDecode for crate::api::engine::SlotChoiceKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::engine::SlotChoiceKind::Append,
            1 => crate::api::engine::SlotChoiceKind::Replace,
            2 => crate::api::engine::SlotChoiceKind::Discard,
            _ => unreachable!("Invalid variant for SlotChoiceKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::engine::SlotUsageDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_used = <u32>::sse_decode(deserializer);
        let mut var_capacity = <u32>::sse_decode(deserializer);
        return crate::api::engine::SlotUsageDto {
            used: var_used,
            capacity: var_capacity,
        };
    }
}

impl SseDecode for crate::api::engine::TieWinnerDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::engine::TieWinnerDto::Player,
            1 => crate::api::engine::TieWinnerDto::Opposition,
            _ => unreachable!("Invalid variant for TieWinnerDto: {}", inner),
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        7 => wire__crate__api__engine__init_app_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__instance__acquire_instance_slot_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__engine__advancement_option_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__flow__allowed_roll_actions_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__engine__apply_roll_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__flow__declare_roll_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__engine__default_room_settings_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__engine__new_character_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__flow__parse_roll_state_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__api__engine__resolve_roll_impl(ptr, rust_vec_len, data_len),
        11 => wire__crate__api__engine__roll_dice_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__flow__roll_state_id_impl(ptr, rust_vec_len, data_len),
        13 => wire__crate__api__flow__roll_transition_impl(ptr, rust_vec_len, data_len),
        14 => wire__crate__api__engine__slot_usage_impl(ptr, rust_vec_len, data_len),
        15 => wire__crate__api__engine__validate_character_impl(ptr, rust_vec_len, data_len),
        16 => wire__crate__api__engine__validate_item_impl(ptr, rust_vec_len, data_len),
        17 => wire__crate__api__engine__validate_room_settings_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::flow::ActorDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Dm => 0.into_dart(),
            Self::Owner => 1.into_dart(),
            Self::Other => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::flow::ActorDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::flow::ActorDto> for crate::api::flow::ActorDto {
    fn into_into_dart(self) -> crate::api::flow::ActorDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::flow::AdvanceStateDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Pendiente => 0.into_dart(),
            Self::Aplicado => 1.into_dart(),
            Self::NoAplica => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::flow::AdvanceStateDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::flow::AdvanceStateDto> for crate::api::flow::AdvanceStateDto {
    fn into_into_dart(self) -> crate::api::flow::AdvanceStateDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::AdvancementChoiceDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.new_skill_name.into_into_dart().into_dart(),
            self.slot.into_into_dart().into_dart(),
            self.replace_index.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::AdvancementChoiceDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::AdvancementChoiceDto>
    for crate::api::engine::AdvancementChoiceDto
{
    fn into_into_dart(self) -> crate::api::engine::AdvancementChoiceDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::AdvancementOptionDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.source_skill_index.into_into_dart().into_dart(),
            self.source_label.into_into_dart().into_dart(),
            self.new_level.into_into_dart().into_dart(),
            self.natural.into_into_dart().into_dart(),
            self.xp_cost.into_into_dart().into_dart(),
            self.xp_available.into_into_dart().into_dart(),
            self.slots_full.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::AdvancementOptionDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::AdvancementOptionDto>
    for crate::api::engine::AdvancementOptionDto
{
    fn into_into_dart(self) -> crate::api::engine::AdvancementOptionDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::flow::AppliedAdvanceDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.xp_gained.into_into_dart().into_dart(),
            self.xp_spent.into_into_dart().into_dart(),
            self.new_skill.into_into_dart().into_dart(),
            self.replaced_index.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::flow::AppliedAdvanceDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::flow::AppliedAdvanceDto> for crate::api::flow::AppliedAdvanceDto {
    fn into_into_dart(self) -> crate::api::flow::AppliedAdvanceDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::ApplyResultDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.character.into_into_dart().into_dart(),
            self.xp_gained.into_into_dart().into_dart(),
            self.xp_spent.into_into_dart().into_dart(),
            self.new_skill.into_into_dart().into_dart(),
            self.replaced_index.into_into_dart().into_dart(),
            self.replaced_skill.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::ApplyResultDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::ApplyResultDto> for crate::api::engine::ApplyResultDto {
    fn into_into_dart(self) -> crate::api::engine::ApplyResultDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::CharacterDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
            self.notes.into_into_dart().into_dart(),
            self.xp.into_into_dart().into_dart(),
            self.skills.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::CharacterDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::CharacterDto> for crate::api::engine::CharacterDto {
    fn into_into_dart(self) -> crate::api::engine::CharacterDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::flow::FlowActionDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.skill.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
            self.dice.into_into_dart().into_dart(),
            self.tie_winner.into_into_dart().into_dart(),
            self.applied.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::flow::FlowActionDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::flow::FlowActionDto> for crate::api::flow::FlowActionDto {
    fn into_into_dart(self) -> crate::api::flow::FlowActionDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::flow::FlowActionKindDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Approve => 0.into_dart(),
            Self::CounterOffer => 1.into_dart(),
            Self::Reject => 2.into_dart(),
            Self::Narrate => 3.into_dart(),
            Self::AcceptCounterOffer => 4.into_dart(),
            Self::Redeclare => 5.into_dart(),
            Self::Withdraw => 6.into_dart(),
            Self::RollOpposition => 7.into_dart(),
            Self::RollPlayer => 8.into_dart(),
            Self::Resolve => 9.into_dart(),
            Self::ApplyAdvance => 10.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::flow::FlowActionKindDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::flow::FlowActionKindDto> for crate::api::flow::FlowActionKindDto {
    fn into_into_dart(self) -> crate::api::flow::FlowActionKindDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::flow::HistoryEntryDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.from.into_into_dart().into_dart(),
            self.to.into_into_dart().into_dart(),
            self.by.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::flow::HistoryEntryDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::flow::HistoryEntryDto> for crate::api::flow::HistoryEntryDto {
    fn into_into_dart(self) -> crate::api::flow::HistoryEntryDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::ItemDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.quantity.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::ItemDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::ItemDto> for crate::api::engine::ItemDto {
    fn into_into_dart(self) -> crate::api::engine::ItemDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::RollOutcomeDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.success.into_into_dart().into_dart(),
            self.player_total.into_into_dart().into_dart(),
            self.opposition_total.into_into_dart().into_dart(),
            self.xp_gained.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::RollOutcomeDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::RollOutcomeDto> for crate::api::engine::RollOutcomeDto {
    fn into_into_dart(self) -> crate::api::engine::RollOutcomeDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::flow::RollRecordDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.state.into_into_dart().into_dart(),
            self.action.into_into_dart().into_dart(),
            self.skill.into_into_dart().into_dart(),
            self.counter_offer.into_into_dart().into_dart(),
            self.dm_note.into_into_dart().into_dart(),
            self.opposition.into_into_dart().into_dart(),
            self.player_roll.into_into_dart().into_dart(),
            self.result.into_into_dart().into_dart(),
            self.narration.into_into_dart().into_dart(),
            self.tie_winner.into_into_dart().into_dart(),
            self.advance.into_into_dart().into_dart(),
            self.applied.into_into_dart().into_dart(),
            self.history.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::flow::RollRecordDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::flow::RollRecordDto> for crate::api::flow::RollRecordDto {
    fn into_into_dart(self) -> crate::api::flow::RollRecordDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::flow::RollResultDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Exito => 0.into_dart(),
            Self::Fallo => 1.into_dart(),
            Self::Narrado => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::flow::RollResultDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::flow::RollResultDto> for crate::api::flow::RollResultDto {
    fn into_into_dart(self) -> crate::api::flow::RollResultDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::flow::RollStateDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Declarada => 0.into_dart(),
            Self::Aprobada => 1.into_dart(),
            Self::Contraoferta => 2.into_dart(),
            Self::Rechazada => 3.into_dart(),
            Self::SinTirada => 4.into_dart(),
            Self::Oposicion => 5.into_dart(),
            Self::Tirada => 6.into_dart(),
            Self::Resuelta => 7.into_dart(),
            Self::Retirada => 8.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::flow::RollStateDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::flow::RollStateDto> for crate::api::flow::RollStateDto {
    fn into_into_dart(self) -> crate::api::flow::RollStateDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::RoomSettingsDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.skill_slots.into_into_dart().into_dart(),
            self.tie_winner.into_into_dart().into_dart(),
            self.xp_same_roll.into_into_dart().into_dart(),
            self.max_dice.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::RoomSettingsDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::RoomSettingsDto> for crate::api::engine::RoomSettingsDto {
    fn into_into_dart(self) -> crate::api::engine::RoomSettingsDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::SkillDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.level.into_into_dart().into_dart(),
            self.permanent.into_into_dart().into_dart(),
            self.derived_from.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::SkillDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::SkillDto> for crate::api::engine::SkillDto {
    fn into_into_dart(self) -> crate::api::engine::SkillDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::flow::SkillRefDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.index.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.level.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::flow::SkillRefDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::flow::SkillRefDto> for crate::api::flow::SkillRefDto {
    fn into_into_dart(self) -> crate::api::flow::SkillRefDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::SlotChoiceKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Append => 0.into_dart(),
            Self::Replace => 1.into_dart(),
            Self::Discard => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::SlotChoiceKind {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::SlotChoiceKind> for crate::api::engine::SlotChoiceKind {
    fn into_into_dart(self) -> crate::api::engine::SlotChoiceKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::SlotUsageDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.used.into_into_dart().into_dart(),
            self.capacity.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::SlotUsageDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::SlotUsageDto> for crate::api::engine::SlotUsageDto {
    fn into_into_dart(self) -> crate::api::engine::SlotUsageDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::engine::TieWinnerDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Player => 0.into_dart(),
            Self::Opposition => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::engine::TieWinnerDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::engine::TieWinnerDto> for crate::api::engine::TieWinnerDto {
    fn into_into_dart(self) -> crate::api::engine::TieWinnerDto {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::flow::ActorDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::flow::ActorDto::Dm => 0,
                crate::api::flow::ActorDto::Owner => 1,
                crate::api::flow::ActorDto::Other => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::flow::AdvanceStateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::flow::AdvanceStateDto::Pendiente => 0,
                crate::api::flow::AdvanceStateDto::Aplicado => 1,
                crate::api::flow::AdvanceStateDto::NoAplica => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::engine::AdvancementChoiceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.new_skill_name, serializer);
        <crate::api::engine::SlotChoiceKind>::sse_encode(self.slot, serializer);
        <u32>::sse_encode(self.replace_index, serializer);
    }
}

impl SseEncode for crate::api::engine::AdvancementOptionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.source_skill_index, serializer);
        <String>::sse_encode(self.source_label, serializer);
        <u8>::sse_encode(self.new_level, serializer);
        <bool>::sse_encode(self.natural, serializer);
        <u32>::sse_encode(self.xp_cost, serializer);
        <u32>::sse_encode(self.xp_available, serializer);
        <bool>::sse_encode(self.slots_full, serializer);
    }
}

impl SseEncode for crate::api::flow::AppliedAdvanceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.xp_gained, serializer);
        <u32>::sse_encode(self.xp_spent, serializer);
        <Option<crate::api::engine::SkillDto>>::sse_encode(self.new_skill, serializer);
        <Option<u32>>::sse_encode(self.replaced_index, serializer);
    }
}

impl SseEncode for crate::api::engine::ApplyResultDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::engine::CharacterDto>::sse_encode(self.character, serializer);
        <u32>::sse_encode(self.xp_gained, serializer);
        <u32>::sse_encode(self.xp_spent, serializer);
        <Option<crate::api::engine::SkillDto>>::sse_encode(self.new_skill, serializer);
        <Option<u32>>::sse_encode(self.replaced_index, serializer);
        <Option<crate::api::engine::SkillDto>>::sse_encode(self.replaced_skill, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::engine::CharacterDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.description, serializer);
        <String>::sse_encode(self.notes, serializer);
        <u32>::sse_encode(self.xp, serializer);
        <Vec<crate::api::engine::SkillDto>>::sse_encode(self.skills, serializer);
    }
}

impl SseEncode for crate::api::flow::FlowActionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::flow::FlowActionKindDto>::sse_encode(self.kind, serializer);
        <Option<crate::api::flow::SkillRefDto>>::sse_encode(self.skill, serializer);
        <Option<String>>::sse_encode(self.text, serializer);
        <Option<Vec<u8>>>::sse_encode(self.dice, serializer);
        <Option<crate::api::engine::TieWinnerDto>>::sse_encode(self.tie_winner, serializer);
        <Option<crate::api::flow::AppliedAdvanceDto>>::sse_encode(self.applied, serializer);
    }
}

impl SseEncode for crate::api::flow::FlowActionKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::flow::FlowActionKindDto::Approve => 0,
                crate::api::flow::FlowActionKindDto::CounterOffer => 1,
                crate::api::flow::FlowActionKindDto::Reject => 2,
                crate::api::flow::FlowActionKindDto::Narrate => 3,
                crate::api::flow::FlowActionKindDto::AcceptCounterOffer => 4,
                crate::api::flow::FlowActionKindDto::Redeclare => 5,
                crate::api::flow::FlowActionKindDto::Withdraw => 6,
                crate::api::flow::FlowActionKindDto::RollOpposition => 7,
                crate::api::flow::FlowActionKindDto::RollPlayer => 8,
                crate::api::flow::FlowActionKindDto::Resolve => 9,
                crate::api::flow::FlowActionKindDto::ApplyAdvance => 10,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::flow::HistoryEntryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::api::flow::RollStateDto>>::sse_encode(self.from, serializer);
        <crate::api::flow::RollStateDto>::sse_encode(self.to, serializer);
        <crate::api::flow::ActorDto>::sse_encode(self.by, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::engine::ItemDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.description, serializer);
        <Option<u32>>::sse_encode(self.value, serializer);
        <u32>::sse_encode(self.quantity, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::flow::FlowActionKindDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::flow::FlowActionKindDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::flow::HistoryEntryDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::flow::HistoryEntryDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::engine::SkillDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::engine::SkillDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::flow::AdvanceStateDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::flow::AdvanceStateDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::engine::AdvancementChoiceDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::engine::AdvancementChoiceDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::engine::AdvancementOptionDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::engine::AdvancementOptionDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::flow::AppliedAdvanceDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::flow::AppliedAdvanceDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::flow::RollResultDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::flow::RollResultDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::flow::RollStateDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::flow::RollStateDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::engine::SkillDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::engine::SkillDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::flow::SkillRefDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::flow::SkillRefDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::engine::TieWinnerDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::engine::TieWinnerDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<u8>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::engine::RollOutcomeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.success, serializer);
        <u32>::sse_encode(self.player_total, serializer);
        <u32>::sse_encode(self.opposition_total, serializer);
        <u32>::sse_encode(self.xp_gained, serializer);
    }
}

impl SseEncode for crate::api::flow::RollRecordDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::flow::RollStateDto>::sse_encode(self.state, serializer);
        <String>::sse_encode(self.action, serializer);
        <crate::api::flow::SkillRefDto>::sse_encode(self.skill, serializer);
        <Option<crate::api::flow::SkillRefDto>>::sse_encode(self.counter_offer, serializer);
        <Option<String>>::sse_encode(self.dm_note, serializer);
        <Option<Vec<u8>>>::sse_encode(self.opposition, serializer);
        <Option<Vec<u8>>>::sse_encode(self.player_roll, serializer);
        <Option<crate::api::flow::RollResultDto>>::sse_encode(self.result, serializer);
        <Option<String>>::sse_encode(self.narration, serializer);
        <Option<crate::api::engine::TieWinnerDto>>::sse_encode(self.tie_winner, serializer);
        <Option<crate::api::flow::AdvanceStateDto>>::sse_encode(self.advance, serializer);
        <Option<crate::api::flow::AppliedAdvanceDto>>::sse_encode(self.applied, serializer);
        <Vec<crate::api::flow::HistoryEntryDto>>::sse_encode(self.history, serializer);
    }
}

impl SseEncode for crate::api::flow::RollResultDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::flow::RollResultDto::Exito => 0,
                crate::api::flow::RollResultDto::Fallo => 1,
                crate::api::flow::RollResultDto::Narrado => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::flow::RollStateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::flow::RollStateDto::Declarada => 0,
                crate::api::flow::RollStateDto::Aprobada => 1,
                crate::api::flow::RollStateDto::Contraoferta => 2,
                crate::api::flow::RollStateDto::Rechazada => 3,
                crate::api::flow::RollStateDto::SinTirada => 4,
                crate::api::flow::RollStateDto::Oposicion => 5,
                crate::api::flow::RollStateDto::Tirada => 6,
                crate::api::flow::RollStateDto::Resuelta => 7,
                crate::api::flow::RollStateDto::Retirada => 8,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::engine::RoomSettingsDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.skill_slots, serializer);
        <crate::api::engine::TieWinnerDto>::sse_encode(self.tie_winner, serializer);
        <bool>::sse_encode(self.xp_same_roll, serializer);
        <u8>::sse_encode(self.max_dice, serializer);
    }
}

impl SseEncode for crate::api::engine::SkillDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <u8>::sse_encode(self.level, serializer);
        <bool>::sse_encode(self.permanent, serializer);
        <Option<String>>::sse_encode(self.derived_from, serializer);
    }
}

impl SseEncode for crate::api::flow::SkillRefDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.index, serializer);
        <String>::sse_encode(self.name, serializer);
        <u8>::sse_encode(self.level, serializer);
    }
}

impl SseEncode for crate::api::engine::SlotChoiceKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::engine::SlotChoiceKind::Append => 0,
                crate::api::engine::SlotChoiceKind::Replace => 1,
                crate::api::engine::SlotChoiceKind::Discard => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::engine::SlotUsageDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.used, serializer);
        <u32>::sse_encode(self.capacity, serializer);
    }
}

impl SseEncode for crate::api::engine::TieWinnerDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::engine::TieWinnerDto::Player => 0,
                crate::api::engine::TieWinnerDto::Opposition => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
