// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';
import 'api/flow.dart';
import 'api/instance.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiEngineInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1623926203;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'rust_lib_kovalt_roller',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  int? crateApiInstanceAcquireInstanceSlot({required int maxSlots});

  AdvancementOptionDto? crateApiEngineAdvancementOption({
    required CharacterDto character,
    required RoomSettingsDto settings,
    required List<int> playerDice,
    required List<int> oppositionDice,
    required int skillIndex,
  });

  List<FlowActionKindDto> crateApiFlowAllowedRollActions({
    required RollStateDto state,
    AdvanceStateDto? advance,
    required ActorDto actor,
  });

  ApplyResultDto crateApiEngineApplyRoll({
    required CharacterDto character,
    required RoomSettingsDto settings,
    required List<int> playerDice,
    required List<int> oppositionDice,
    required int skillIndex,
    AdvancementChoiceDto? choice,
  });

  RollRecordDto crateApiFlowDeclareRoll({required String action, required SkillRefDto skill});

  RoomSettingsDto crateApiEngineDefaultRoomSettings();

  Future<void> crateApiEngineInitApp();

  CharacterDto crateApiEngineNewCharacter({required String name, required String description});

  RollStateDto? crateApiFlowParseRollState({required String id});

  RollOutcomeDto crateApiEngineResolveRoll({
    required List<int> playerDice,
    required List<int> oppositionDice,
    required RoomSettingsDto settings,
  });

  Uint8List crateApiEngineRollDice({required int count, required int maxDice});

  String crateApiFlowRollStateId({required RollStateDto state});

  RollRecordDto crateApiFlowRollTransition({
    required RollRecordDto record,
    required FlowActionDto action,
    required ActorDto actor,
    required int maxDice,
  });

  SlotUsageDto crateApiEngineSlotUsage({required CharacterDto character, required RoomSettingsDto settings});

  List<String> crateApiEngineValidateCharacter({required CharacterDto character, required RoomSettingsDto settings});

  String? crateApiEngineValidateItem({required ItemDto item});

  String? crateApiEngineValidateRoomSettings({required RoomSettingsDto settings});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  int? crateApiInstanceAcquireInstanceSlot({required int maxSlots}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(maxSlots, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_opt_box_autoadd_u_32, decodeErrorData: null),
        constMeta: kCrateApiInstanceAcquireInstanceSlotConstMeta,
        argValues: [maxSlots],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInstanceAcquireInstanceSlotConstMeta =>
      const TaskConstMeta(debugName: "acquire_instance_slot", argNames: ["maxSlots"]);

  @override
  AdvancementOptionDto? crateApiEngineAdvancementOption({
    required CharacterDto character,
    required RoomSettingsDto settings,
    required List<int> playerDice,
    required List<int> oppositionDice,
    required int skillIndex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_character_dto(character, serializer);
          sse_encode_box_autoadd_room_settings_dto(settings, serializer);
          sse_encode_list_prim_u_8_loose(playerDice, serializer);
          sse_encode_list_prim_u_8_loose(oppositionDice, serializer);
          sse_encode_u_32(skillIndex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_advancement_option_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineAdvancementOptionConstMeta,
        argValues: [character, settings, playerDice, oppositionDice, skillIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineAdvancementOptionConstMeta => const TaskConstMeta(
    debugName: "advancement_option",
    argNames: ["character", "settings", "playerDice", "oppositionDice", "skillIndex"],
  );

  @override
  List<FlowActionKindDto> crateApiFlowAllowedRollActions({
    required RollStateDto state,
    AdvanceStateDto? advance,
    required ActorDto actor,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_roll_state_dto(state, serializer);
          sse_encode_opt_box_autoadd_advance_state_dto(advance, serializer);
          sse_encode_actor_dto(actor, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_flow_action_kind_dto, decodeErrorData: null),
        constMeta: kCrateApiFlowAllowedRollActionsConstMeta,
        argValues: [state, advance, actor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlowAllowedRollActionsConstMeta =>
      const TaskConstMeta(debugName: "allowed_roll_actions", argNames: ["state", "advance", "actor"]);

  @override
  ApplyResultDto crateApiEngineApplyRoll({
    required CharacterDto character,
    required RoomSettingsDto settings,
    required List<int> playerDice,
    required List<int> oppositionDice,
    required int skillIndex,
    AdvancementChoiceDto? choice,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_character_dto(character, serializer);
          sse_encode_box_autoadd_room_settings_dto(settings, serializer);
          sse_encode_list_prim_u_8_loose(playerDice, serializer);
          sse_encode_list_prim_u_8_loose(oppositionDice, serializer);
          sse_encode_u_32(skillIndex, serializer);
          sse_encode_opt_box_autoadd_advancement_choice_dto(choice, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_apply_result_dto, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiEngineApplyRollConstMeta,
        argValues: [character, settings, playerDice, oppositionDice, skillIndex, choice],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApplyRollConstMeta => const TaskConstMeta(
    debugName: "apply_roll",
    argNames: ["character", "settings", "playerDice", "oppositionDice", "skillIndex", "choice"],
  );

  @override
  RollRecordDto crateApiFlowDeclareRoll({required String action, required SkillRefDto skill}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(action, serializer);
          sse_encode_box_autoadd_skill_ref_dto(skill, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_roll_record_dto, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiFlowDeclareRollConstMeta,
        argValues: [action, skill],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlowDeclareRollConstMeta =>
      const TaskConstMeta(debugName: "declare_roll", argNames: ["action", "skill"]);

  @override
  RoomSettingsDto crateApiEngineDefaultRoomSettings() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_room_settings_dto, decodeErrorData: null),
        constMeta: kCrateApiEngineDefaultRoomSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineDefaultRoomSettingsConstMeta =>
      const TaskConstMeta(debugName: "default_room_settings", argNames: []);

  @override
  Future<void> crateApiEngineInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: null),
        constMeta: kCrateApiEngineInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineInitAppConstMeta => const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  CharacterDto crateApiEngineNewCharacter({required String name, required String description}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(description, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_character_dto, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiEngineNewCharacterConstMeta,
        argValues: [name, description],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineNewCharacterConstMeta =>
      const TaskConstMeta(debugName: "new_character", argNames: ["name", "description"]);

  @override
  RollStateDto? crateApiFlowParseRollState({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_opt_box_autoadd_roll_state_dto, decodeErrorData: null),
        constMeta: kCrateApiFlowParseRollStateConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlowParseRollStateConstMeta =>
      const TaskConstMeta(debugName: "parse_roll_state", argNames: ["id"]);

  @override
  RollOutcomeDto crateApiEngineResolveRoll({
    required List<int> playerDice,
    required List<int> oppositionDice,
    required RoomSettingsDto settings,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(playerDice, serializer);
          sse_encode_list_prim_u_8_loose(oppositionDice, serializer);
          sse_encode_box_autoadd_room_settings_dto(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_roll_outcome_dto, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiEngineResolveRollConstMeta,
        argValues: [playerDice, oppositionDice, settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineResolveRollConstMeta =>
      const TaskConstMeta(debugName: "resolve_roll", argNames: ["playerDice", "oppositionDice", "settings"]);

  @override
  Uint8List crateApiEngineRollDice({required int count, required int maxDice}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(count, serializer);
          sse_encode_u_8(maxDice, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEngineRollDiceConstMeta,
        argValues: [count, maxDice],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRollDiceConstMeta =>
      const TaskConstMeta(debugName: "roll_dice", argNames: ["count", "maxDice"]);

  @override
  String crateApiFlowRollStateId({required RollStateDto state}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_roll_state_dto(state, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: null),
        constMeta: kCrateApiFlowRollStateIdConstMeta,
        argValues: [state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlowRollStateIdConstMeta =>
      const TaskConstMeta(debugName: "roll_state_id", argNames: ["state"]);

  @override
  RollRecordDto crateApiFlowRollTransition({
    required RollRecordDto record,
    required FlowActionDto action,
    required ActorDto actor,
    required int maxDice,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_roll_record_dto(record, serializer);
          sse_encode_box_autoadd_flow_action_dto(action, serializer);
          sse_encode_actor_dto(actor, serializer);
          sse_encode_u_8(maxDice, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_roll_record_dto, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiFlowRollTransitionConstMeta,
        argValues: [record, action, actor, maxDice],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlowRollTransitionConstMeta =>
      const TaskConstMeta(debugName: "roll_transition", argNames: ["record", "action", "actor", "maxDice"]);

  @override
  SlotUsageDto crateApiEngineSlotUsage({required CharacterDto character, required RoomSettingsDto settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_character_dto(character, serializer);
          sse_encode_box_autoadd_room_settings_dto(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_slot_usage_dto, decodeErrorData: null),
        constMeta: kCrateApiEngineSlotUsageConstMeta,
        argValues: [character, settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineSlotUsageConstMeta =>
      const TaskConstMeta(debugName: "slot_usage", argNames: ["character", "settings"]);

  @override
  List<String> crateApiEngineValidateCharacter({required CharacterDto character, required RoomSettingsDto settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_character_dto(character, serializer);
          sse_encode_box_autoadd_room_settings_dto(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_String, decodeErrorData: null),
        constMeta: kCrateApiEngineValidateCharacterConstMeta,
        argValues: [character, settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineValidateCharacterConstMeta =>
      const TaskConstMeta(debugName: "validate_character", argNames: ["character", "settings"]);

  @override
  String? crateApiEngineValidateItem({required ItemDto item}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_item_dto(item, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_opt_String, decodeErrorData: null),
        constMeta: kCrateApiEngineValidateItemConstMeta,
        argValues: [item],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineValidateItemConstMeta =>
      const TaskConstMeta(debugName: "validate_item", argNames: ["item"]);

  @override
  String? crateApiEngineValidateRoomSettings({required RoomSettingsDto settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_room_settings_dto(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_opt_String, decodeErrorData: null),
        constMeta: kCrateApiEngineValidateRoomSettingsConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineValidateRoomSettingsConstMeta =>
      const TaskConstMeta(debugName: "validate_room_settings", argNames: ["settings"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ActorDto dco_decode_actor_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ActorDto.values[raw as int];
  }

  @protected
  AdvanceStateDto dco_decode_advance_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AdvanceStateDto.values[raw as int];
  }

  @protected
  AdvancementChoiceDto dco_decode_advancement_choice_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AdvancementChoiceDto(
      newSkillName: dco_decode_String(arr[0]),
      slot: dco_decode_slot_choice_kind(arr[1]),
      replaceIndex: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  AdvancementOptionDto dco_decode_advancement_option_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AdvancementOptionDto(
      sourceSkillIndex: dco_decode_u_32(arr[0]),
      sourceLabel: dco_decode_String(arr[1]),
      newLevel: dco_decode_u_8(arr[2]),
      natural: dco_decode_bool(arr[3]),
      xpCost: dco_decode_u_32(arr[4]),
      xpAvailable: dco_decode_u_32(arr[5]),
      slotsFull: dco_decode_bool(arr[6]),
    );
  }

  @protected
  AppliedAdvanceDto dco_decode_applied_advance_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppliedAdvanceDto(
      xpGained: dco_decode_u_32(arr[0]),
      xpSpent: dco_decode_u_32(arr[1]),
      newSkill: dco_decode_opt_box_autoadd_skill_dto(arr[2]),
      replacedIndex: dco_decode_opt_box_autoadd_u_32(arr[3]),
    );
  }

  @protected
  ApplyResultDto dco_decode_apply_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ApplyResultDto(
      character: dco_decode_character_dto(arr[0]),
      xpGained: dco_decode_u_32(arr[1]),
      xpSpent: dco_decode_u_32(arr[2]),
      newSkill: dco_decode_opt_box_autoadd_skill_dto(arr[3]),
      replacedIndex: dco_decode_opt_box_autoadd_u_32(arr[4]),
      replacedSkill: dco_decode_opt_box_autoadd_skill_dto(arr[5]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AdvanceStateDto dco_decode_box_autoadd_advance_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_advance_state_dto(raw);
  }

  @protected
  AdvancementChoiceDto dco_decode_box_autoadd_advancement_choice_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_advancement_choice_dto(raw);
  }

  @protected
  AdvancementOptionDto dco_decode_box_autoadd_advancement_option_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_advancement_option_dto(raw);
  }

  @protected
  AppliedAdvanceDto dco_decode_box_autoadd_applied_advance_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_applied_advance_dto(raw);
  }

  @protected
  CharacterDto dco_decode_box_autoadd_character_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_character_dto(raw);
  }

  @protected
  FlowActionDto dco_decode_box_autoadd_flow_action_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flow_action_dto(raw);
  }

  @protected
  ItemDto dco_decode_box_autoadd_item_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_item_dto(raw);
  }

  @protected
  RollRecordDto dco_decode_box_autoadd_roll_record_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_roll_record_dto(raw);
  }

  @protected
  RollResultDto dco_decode_box_autoadd_roll_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_roll_result_dto(raw);
  }

  @protected
  RollStateDto dco_decode_box_autoadd_roll_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_roll_state_dto(raw);
  }

  @protected
  RoomSettingsDto dco_decode_box_autoadd_room_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_room_settings_dto(raw);
  }

  @protected
  SkillDto dco_decode_box_autoadd_skill_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_skill_dto(raw);
  }

  @protected
  SkillRefDto dco_decode_box_autoadd_skill_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_skill_ref_dto(raw);
  }

  @protected
  TieWinnerDto dco_decode_box_autoadd_tie_winner_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tie_winner_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CharacterDto dco_decode_character_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CharacterDto(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      notes: dco_decode_String(arr[2]),
      xp: dco_decode_u_32(arr[3]),
      skills: dco_decode_list_skill_dto(arr[4]),
    );
  }

  @protected
  FlowActionDto dco_decode_flow_action_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FlowActionDto(
      kind: dco_decode_flow_action_kind_dto(arr[0]),
      skill: dco_decode_opt_box_autoadd_skill_ref_dto(arr[1]),
      text: dco_decode_opt_String(arr[2]),
      dice: dco_decode_opt_list_prim_u_8_strict(arr[3]),
      tieWinner: dco_decode_opt_box_autoadd_tie_winner_dto(arr[4]),
      applied: dco_decode_opt_box_autoadd_applied_advance_dto(arr[5]),
    );
  }

  @protected
  FlowActionKindDto dco_decode_flow_action_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlowActionKindDto.values[raw as int];
  }

  @protected
  HistoryEntryDto dco_decode_history_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HistoryEntryDto(
      from: dco_decode_opt_box_autoadd_roll_state_dto(arr[0]),
      to: dco_decode_roll_state_dto(arr[1]),
      by: dco_decode_actor_dto(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ItemDto dco_decode_item_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ItemDto(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      value: dco_decode_opt_box_autoadd_u_32(arr[2]),
      quantity: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FlowActionKindDto> dco_decode_list_flow_action_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_flow_action_kind_dto).toList();
  }

  @protected
  List<HistoryEntryDto> dco_decode_list_history_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_history_entry_dto).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SkillDto> dco_decode_list_skill_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_skill_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AdvanceStateDto? dco_decode_opt_box_autoadd_advance_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_advance_state_dto(raw);
  }

  @protected
  AdvancementChoiceDto? dco_decode_opt_box_autoadd_advancement_choice_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_advancement_choice_dto(raw);
  }

  @protected
  AdvancementOptionDto? dco_decode_opt_box_autoadd_advancement_option_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_advancement_option_dto(raw);
  }

  @protected
  AppliedAdvanceDto? dco_decode_opt_box_autoadd_applied_advance_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_applied_advance_dto(raw);
  }

  @protected
  RollResultDto? dco_decode_opt_box_autoadd_roll_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_roll_result_dto(raw);
  }

  @protected
  RollStateDto? dco_decode_opt_box_autoadd_roll_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_roll_state_dto(raw);
  }

  @protected
  SkillDto? dco_decode_opt_box_autoadd_skill_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_skill_dto(raw);
  }

  @protected
  SkillRefDto? dco_decode_opt_box_autoadd_skill_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_skill_ref_dto(raw);
  }

  @protected
  TieWinnerDto? dco_decode_opt_box_autoadd_tie_winner_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_tie_winner_dto(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  RollOutcomeDto dco_decode_roll_outcome_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RollOutcomeDto(
      success: dco_decode_bool(arr[0]),
      playerTotal: dco_decode_u_32(arr[1]),
      oppositionTotal: dco_decode_u_32(arr[2]),
      xpGained: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  RollRecordDto dco_decode_roll_record_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13) throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return RollRecordDto(
      state: dco_decode_roll_state_dto(arr[0]),
      action: dco_decode_String(arr[1]),
      skill: dco_decode_skill_ref_dto(arr[2]),
      counterOffer: dco_decode_opt_box_autoadd_skill_ref_dto(arr[3]),
      dmNote: dco_decode_opt_String(arr[4]),
      opposition: dco_decode_opt_list_prim_u_8_strict(arr[5]),
      playerRoll: dco_decode_opt_list_prim_u_8_strict(arr[6]),
      result: dco_decode_opt_box_autoadd_roll_result_dto(arr[7]),
      narration: dco_decode_opt_String(arr[8]),
      tieWinner: dco_decode_opt_box_autoadd_tie_winner_dto(arr[9]),
      advance: dco_decode_opt_box_autoadd_advance_state_dto(arr[10]),
      applied: dco_decode_opt_box_autoadd_applied_advance_dto(arr[11]),
      history: dco_decode_list_history_entry_dto(arr[12]),
    );
  }

  @protected
  RollResultDto dco_decode_roll_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RollResultDto.values[raw as int];
  }

  @protected
  RollStateDto dco_decode_roll_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RollStateDto.values[raw as int];
  }

  @protected
  RoomSettingsDto dco_decode_room_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RoomSettingsDto(
      skillSlots: dco_decode_u_8(arr[0]),
      tieWinner: dco_decode_tie_winner_dto(arr[1]),
      xpSameRoll: dco_decode_bool(arr[2]),
      maxDice: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  SkillDto dco_decode_skill_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SkillDto(
      name: dco_decode_String(arr[0]),
      level: dco_decode_u_8(arr[1]),
      permanent: dco_decode_bool(arr[2]),
      derivedFrom: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  SkillRefDto dco_decode_skill_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SkillRefDto(index: dco_decode_u_32(arr[0]), name: dco_decode_String(arr[1]), level: dco_decode_u_8(arr[2]));
  }

  @protected
  SlotChoiceKind dco_decode_slot_choice_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SlotChoiceKind.values[raw as int];
  }

  @protected
  SlotUsageDto dco_decode_slot_usage_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SlotUsageDto(used: dco_decode_u_32(arr[0]), capacity: dco_decode_u_32(arr[1]));
  }

  @protected
  TieWinnerDto dco_decode_tie_winner_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TieWinnerDto.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActorDto sse_decode_actor_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ActorDto.values[inner];
  }

  @protected
  AdvanceStateDto sse_decode_advance_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AdvanceStateDto.values[inner];
  }

  @protected
  AdvancementChoiceDto sse_decode_advancement_choice_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_newSkillName = sse_decode_String(deserializer);
    var var_slot = sse_decode_slot_choice_kind(deserializer);
    var var_replaceIndex = sse_decode_u_32(deserializer);
    return AdvancementChoiceDto(newSkillName: var_newSkillName, slot: var_slot, replaceIndex: var_replaceIndex);
  }

  @protected
  AdvancementOptionDto sse_decode_advancement_option_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceSkillIndex = sse_decode_u_32(deserializer);
    var var_sourceLabel = sse_decode_String(deserializer);
    var var_newLevel = sse_decode_u_8(deserializer);
    var var_natural = sse_decode_bool(deserializer);
    var var_xpCost = sse_decode_u_32(deserializer);
    var var_xpAvailable = sse_decode_u_32(deserializer);
    var var_slotsFull = sse_decode_bool(deserializer);
    return AdvancementOptionDto(
      sourceSkillIndex: var_sourceSkillIndex,
      sourceLabel: var_sourceLabel,
      newLevel: var_newLevel,
      natural: var_natural,
      xpCost: var_xpCost,
      xpAvailable: var_xpAvailable,
      slotsFull: var_slotsFull,
    );
  }

  @protected
  AppliedAdvanceDto sse_decode_applied_advance_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_xpGained = sse_decode_u_32(deserializer);
    var var_xpSpent = sse_decode_u_32(deserializer);
    var var_newSkill = sse_decode_opt_box_autoadd_skill_dto(deserializer);
    var var_replacedIndex = sse_decode_opt_box_autoadd_u_32(deserializer);
    return AppliedAdvanceDto(
      xpGained: var_xpGained,
      xpSpent: var_xpSpent,
      newSkill: var_newSkill,
      replacedIndex: var_replacedIndex,
    );
  }

  @protected
  ApplyResultDto sse_decode_apply_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_character = sse_decode_character_dto(deserializer);
    var var_xpGained = sse_decode_u_32(deserializer);
    var var_xpSpent = sse_decode_u_32(deserializer);
    var var_newSkill = sse_decode_opt_box_autoadd_skill_dto(deserializer);
    var var_replacedIndex = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_replacedSkill = sse_decode_opt_box_autoadd_skill_dto(deserializer);
    return ApplyResultDto(
      character: var_character,
      xpGained: var_xpGained,
      xpSpent: var_xpSpent,
      newSkill: var_newSkill,
      replacedIndex: var_replacedIndex,
      replacedSkill: var_replacedSkill,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AdvanceStateDto sse_decode_box_autoadd_advance_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_advance_state_dto(deserializer));
  }

  @protected
  AdvancementChoiceDto sse_decode_box_autoadd_advancement_choice_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_advancement_choice_dto(deserializer));
  }

  @protected
  AdvancementOptionDto sse_decode_box_autoadd_advancement_option_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_advancement_option_dto(deserializer));
  }

  @protected
  AppliedAdvanceDto sse_decode_box_autoadd_applied_advance_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_applied_advance_dto(deserializer));
  }

  @protected
  CharacterDto sse_decode_box_autoadd_character_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_character_dto(deserializer));
  }

  @protected
  FlowActionDto sse_decode_box_autoadd_flow_action_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flow_action_dto(deserializer));
  }

  @protected
  ItemDto sse_decode_box_autoadd_item_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_item_dto(deserializer));
  }

  @protected
  RollRecordDto sse_decode_box_autoadd_roll_record_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_roll_record_dto(deserializer));
  }

  @protected
  RollResultDto sse_decode_box_autoadd_roll_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_roll_result_dto(deserializer));
  }

  @protected
  RollStateDto sse_decode_box_autoadd_roll_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_roll_state_dto(deserializer));
  }

  @protected
  RoomSettingsDto sse_decode_box_autoadd_room_settings_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_room_settings_dto(deserializer));
  }

  @protected
  SkillDto sse_decode_box_autoadd_skill_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_skill_dto(deserializer));
  }

  @protected
  SkillRefDto sse_decode_box_autoadd_skill_ref_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_skill_ref_dto(deserializer));
  }

  @protected
  TieWinnerDto sse_decode_box_autoadd_tie_winner_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tie_winner_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CharacterDto sse_decode_character_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    var var_xp = sse_decode_u_32(deserializer);
    var var_skills = sse_decode_list_skill_dto(deserializer);
    return CharacterDto(name: var_name, description: var_description, notes: var_notes, xp: var_xp, skills: var_skills);
  }

  @protected
  FlowActionDto sse_decode_flow_action_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_flow_action_kind_dto(deserializer);
    var var_skill = sse_decode_opt_box_autoadd_skill_ref_dto(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_dice = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_tieWinner = sse_decode_opt_box_autoadd_tie_winner_dto(deserializer);
    var var_applied = sse_decode_opt_box_autoadd_applied_advance_dto(deserializer);
    return FlowActionDto(
      kind: var_kind,
      skill: var_skill,
      text: var_text,
      dice: var_dice,
      tieWinner: var_tieWinner,
      applied: var_applied,
    );
  }

  @protected
  FlowActionKindDto sse_decode_flow_action_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FlowActionKindDto.values[inner];
  }

  @protected
  HistoryEntryDto sse_decode_history_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_from = sse_decode_opt_box_autoadd_roll_state_dto(deserializer);
    var var_to = sse_decode_roll_state_dto(deserializer);
    var var_by = sse_decode_actor_dto(deserializer);
    return HistoryEntryDto(from: var_from, to: var_to, by: var_by);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ItemDto sse_decode_item_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_value = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_quantity = sse_decode_u_32(deserializer);
    return ItemDto(name: var_name, description: var_description, value: var_value, quantity: var_quantity);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FlowActionKindDto> sse_decode_list_flow_action_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FlowActionKindDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_flow_action_kind_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<HistoryEntryDto> sse_decode_list_history_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistoryEntryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_history_entry_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SkillDto> sse_decode_list_skill_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SkillDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_skill_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AdvanceStateDto? sse_decode_opt_box_autoadd_advance_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_advance_state_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AdvancementChoiceDto? sse_decode_opt_box_autoadd_advancement_choice_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_advancement_choice_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AdvancementOptionDto? sse_decode_opt_box_autoadd_advancement_option_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_advancement_option_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AppliedAdvanceDto? sse_decode_opt_box_autoadd_applied_advance_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_applied_advance_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RollResultDto? sse_decode_opt_box_autoadd_roll_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_roll_result_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RollStateDto? sse_decode_opt_box_autoadd_roll_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_roll_state_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SkillDto? sse_decode_opt_box_autoadd_skill_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_skill_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SkillRefDto? sse_decode_opt_box_autoadd_skill_ref_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_skill_ref_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TieWinnerDto? sse_decode_opt_box_autoadd_tie_winner_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_tie_winner_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RollOutcomeDto sse_decode_roll_outcome_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_playerTotal = sse_decode_u_32(deserializer);
    var var_oppositionTotal = sse_decode_u_32(deserializer);
    var var_xpGained = sse_decode_u_32(deserializer);
    return RollOutcomeDto(
      success: var_success,
      playerTotal: var_playerTotal,
      oppositionTotal: var_oppositionTotal,
      xpGained: var_xpGained,
    );
  }

  @protected
  RollRecordDto sse_decode_roll_record_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_roll_state_dto(deserializer);
    var var_action = sse_decode_String(deserializer);
    var var_skill = sse_decode_skill_ref_dto(deserializer);
    var var_counterOffer = sse_decode_opt_box_autoadd_skill_ref_dto(deserializer);
    var var_dmNote = sse_decode_opt_String(deserializer);
    var var_opposition = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_playerRoll = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_result = sse_decode_opt_box_autoadd_roll_result_dto(deserializer);
    var var_narration = sse_decode_opt_String(deserializer);
    var var_tieWinner = sse_decode_opt_box_autoadd_tie_winner_dto(deserializer);
    var var_advance = sse_decode_opt_box_autoadd_advance_state_dto(deserializer);
    var var_applied = sse_decode_opt_box_autoadd_applied_advance_dto(deserializer);
    var var_history = sse_decode_list_history_entry_dto(deserializer);
    return RollRecordDto(
      state: var_state,
      action: var_action,
      skill: var_skill,
      counterOffer: var_counterOffer,
      dmNote: var_dmNote,
      opposition: var_opposition,
      playerRoll: var_playerRoll,
      result: var_result,
      narration: var_narration,
      tieWinner: var_tieWinner,
      advance: var_advance,
      applied: var_applied,
      history: var_history,
    );
  }

  @protected
  RollResultDto sse_decode_roll_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RollResultDto.values[inner];
  }

  @protected
  RollStateDto sse_decode_roll_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RollStateDto.values[inner];
  }

  @protected
  RoomSettingsDto sse_decode_room_settings_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_skillSlots = sse_decode_u_8(deserializer);
    var var_tieWinner = sse_decode_tie_winner_dto(deserializer);
    var var_xpSameRoll = sse_decode_bool(deserializer);
    var var_maxDice = sse_decode_u_8(deserializer);
    return RoomSettingsDto(
      skillSlots: var_skillSlots,
      tieWinner: var_tieWinner,
      xpSameRoll: var_xpSameRoll,
      maxDice: var_maxDice,
    );
  }

  @protected
  SkillDto sse_decode_skill_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_level = sse_decode_u_8(deserializer);
    var var_permanent = sse_decode_bool(deserializer);
    var var_derivedFrom = sse_decode_opt_String(deserializer);
    return SkillDto(name: var_name, level: var_level, permanent: var_permanent, derivedFrom: var_derivedFrom);
  }

  @protected
  SkillRefDto sse_decode_skill_ref_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_level = sse_decode_u_8(deserializer);
    return SkillRefDto(index: var_index, name: var_name, level: var_level);
  }

  @protected
  SlotChoiceKind sse_decode_slot_choice_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SlotChoiceKind.values[inner];
  }

  @protected
  SlotUsageDto sse_decode_slot_usage_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_used = sse_decode_u_32(deserializer);
    var var_capacity = sse_decode_u_32(deserializer);
    return SlotUsageDto(used: var_used, capacity: var_capacity);
  }

  @protected
  TieWinnerDto sse_decode_tie_winner_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TieWinnerDto.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_actor_dto(ActorDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_advance_state_dto(AdvanceStateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_advancement_choice_dto(AdvancementChoiceDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.newSkillName, serializer);
    sse_encode_slot_choice_kind(self.slot, serializer);
    sse_encode_u_32(self.replaceIndex, serializer);
  }

  @protected
  void sse_encode_advancement_option_dto(AdvancementOptionDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.sourceSkillIndex, serializer);
    sse_encode_String(self.sourceLabel, serializer);
    sse_encode_u_8(self.newLevel, serializer);
    sse_encode_bool(self.natural, serializer);
    sse_encode_u_32(self.xpCost, serializer);
    sse_encode_u_32(self.xpAvailable, serializer);
    sse_encode_bool(self.slotsFull, serializer);
  }

  @protected
  void sse_encode_applied_advance_dto(AppliedAdvanceDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.xpGained, serializer);
    sse_encode_u_32(self.xpSpent, serializer);
    sse_encode_opt_box_autoadd_skill_dto(self.newSkill, serializer);
    sse_encode_opt_box_autoadd_u_32(self.replacedIndex, serializer);
  }

  @protected
  void sse_encode_apply_result_dto(ApplyResultDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_character_dto(self.character, serializer);
    sse_encode_u_32(self.xpGained, serializer);
    sse_encode_u_32(self.xpSpent, serializer);
    sse_encode_opt_box_autoadd_skill_dto(self.newSkill, serializer);
    sse_encode_opt_box_autoadd_u_32(self.replacedIndex, serializer);
    sse_encode_opt_box_autoadd_skill_dto(self.replacedSkill, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_advance_state_dto(AdvanceStateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_advance_state_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_advancement_choice_dto(AdvancementChoiceDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_advancement_choice_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_advancement_option_dto(AdvancementOptionDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_advancement_option_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_applied_advance_dto(AppliedAdvanceDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_applied_advance_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_character_dto(CharacterDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_character_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flow_action_dto(FlowActionDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flow_action_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_item_dto(ItemDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_item_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_roll_record_dto(RollRecordDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_roll_record_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_roll_result_dto(RollResultDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_roll_result_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_roll_state_dto(RollStateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_roll_state_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_room_settings_dto(RoomSettingsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_room_settings_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_skill_dto(SkillDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_skill_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_skill_ref_dto(SkillRefDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_skill_ref_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tie_winner_dto(TieWinnerDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tie_winner_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_character_dto(CharacterDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.notes, serializer);
    sse_encode_u_32(self.xp, serializer);
    sse_encode_list_skill_dto(self.skills, serializer);
  }

  @protected
  void sse_encode_flow_action_dto(FlowActionDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flow_action_kind_dto(self.kind, serializer);
    sse_encode_opt_box_autoadd_skill_ref_dto(self.skill, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.dice, serializer);
    sse_encode_opt_box_autoadd_tie_winner_dto(self.tieWinner, serializer);
    sse_encode_opt_box_autoadd_applied_advance_dto(self.applied, serializer);
  }

  @protected
  void sse_encode_flow_action_kind_dto(FlowActionKindDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_history_entry_dto(HistoryEntryDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_roll_state_dto(self.from, serializer);
    sse_encode_roll_state_dto(self.to, serializer);
    sse_encode_actor_dto(self.by, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_item_dto(ItemDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_opt_box_autoadd_u_32(self.value, serializer);
    sse_encode_u_32(self.quantity, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_flow_action_kind_dto(List<FlowActionKindDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_flow_action_kind_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_history_entry_dto(List<HistoryEntryDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_history_entry_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_skill_dto(List<SkillDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_skill_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_advance_state_dto(AdvanceStateDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_advance_state_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_advancement_choice_dto(AdvancementChoiceDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_advancement_choice_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_advancement_option_dto(AdvancementOptionDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_advancement_option_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_applied_advance_dto(AppliedAdvanceDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_applied_advance_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_roll_result_dto(RollResultDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_roll_result_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_roll_state_dto(RollStateDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_roll_state_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_skill_dto(SkillDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_skill_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_skill_ref_dto(SkillRefDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_skill_ref_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_tie_winner_dto(TieWinnerDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_tie_winner_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_roll_outcome_dto(RollOutcomeDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_u_32(self.playerTotal, serializer);
    sse_encode_u_32(self.oppositionTotal, serializer);
    sse_encode_u_32(self.xpGained, serializer);
  }

  @protected
  void sse_encode_roll_record_dto(RollRecordDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_roll_state_dto(self.state, serializer);
    sse_encode_String(self.action, serializer);
    sse_encode_skill_ref_dto(self.skill, serializer);
    sse_encode_opt_box_autoadd_skill_ref_dto(self.counterOffer, serializer);
    sse_encode_opt_String(self.dmNote, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.opposition, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.playerRoll, serializer);
    sse_encode_opt_box_autoadd_roll_result_dto(self.result, serializer);
    sse_encode_opt_String(self.narration, serializer);
    sse_encode_opt_box_autoadd_tie_winner_dto(self.tieWinner, serializer);
    sse_encode_opt_box_autoadd_advance_state_dto(self.advance, serializer);
    sse_encode_opt_box_autoadd_applied_advance_dto(self.applied, serializer);
    sse_encode_list_history_entry_dto(self.history, serializer);
  }

  @protected
  void sse_encode_roll_result_dto(RollResultDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_roll_state_dto(RollStateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_room_settings_dto(RoomSettingsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.skillSlots, serializer);
    sse_encode_tie_winner_dto(self.tieWinner, serializer);
    sse_encode_bool(self.xpSameRoll, serializer);
    sse_encode_u_8(self.maxDice, serializer);
  }

  @protected
  void sse_encode_skill_dto(SkillDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_8(self.level, serializer);
    sse_encode_bool(self.permanent, serializer);
    sse_encode_opt_String(self.derivedFrom, serializer);
  }

  @protected
  void sse_encode_skill_ref_dto(SkillRefDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_8(self.level, serializer);
  }

  @protected
  void sse_encode_slot_choice_kind(SlotChoiceKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_slot_usage_dto(SlotUsageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.used, serializer);
    sse_encode_u_32(self.capacity, serializer);
  }

  @protected
  void sse_encode_tie_winner_dto(TieWinnerDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
