// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/engine.dart';
import 'api/flow.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActorDto dco_decode_actor_dto(dynamic raw);

  @protected
  AdvanceStateDto dco_decode_advance_state_dto(dynamic raw);

  @protected
  AdvancementChoiceDto dco_decode_advancement_choice_dto(dynamic raw);

  @protected
  AdvancementOptionDto dco_decode_advancement_option_dto(dynamic raw);

  @protected
  AppliedAdvanceDto dco_decode_applied_advance_dto(dynamic raw);

  @protected
  ApplyResultDto dco_decode_apply_result_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AdvanceStateDto dco_decode_box_autoadd_advance_state_dto(dynamic raw);

  @protected
  AdvancementChoiceDto dco_decode_box_autoadd_advancement_choice_dto(dynamic raw);

  @protected
  AdvancementOptionDto dco_decode_box_autoadd_advancement_option_dto(dynamic raw);

  @protected
  AppliedAdvanceDto dco_decode_box_autoadd_applied_advance_dto(dynamic raw);

  @protected
  CharacterDto dco_decode_box_autoadd_character_dto(dynamic raw);

  @protected
  FlowActionDto dco_decode_box_autoadd_flow_action_dto(dynamic raw);

  @protected
  ItemDto dco_decode_box_autoadd_item_dto(dynamic raw);

  @protected
  RollRecordDto dco_decode_box_autoadd_roll_record_dto(dynamic raw);

  @protected
  RollResultDto dco_decode_box_autoadd_roll_result_dto(dynamic raw);

  @protected
  RollStateDto dco_decode_box_autoadd_roll_state_dto(dynamic raw);

  @protected
  RoomSettingsDto dco_decode_box_autoadd_room_settings_dto(dynamic raw);

  @protected
  SkillDto dco_decode_box_autoadd_skill_dto(dynamic raw);

  @protected
  SkillRefDto dco_decode_box_autoadd_skill_ref_dto(dynamic raw);

  @protected
  TieWinnerDto dco_decode_box_autoadd_tie_winner_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CharacterDto dco_decode_character_dto(dynamic raw);

  @protected
  FlowActionDto dco_decode_flow_action_dto(dynamic raw);

  @protected
  FlowActionKindDto dco_decode_flow_action_kind_dto(dynamic raw);

  @protected
  HistoryEntryDto dco_decode_history_entry_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ItemDto dco_decode_item_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FlowActionKindDto> dco_decode_list_flow_action_kind_dto(dynamic raw);

  @protected
  List<HistoryEntryDto> dco_decode_list_history_entry_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SkillDto> dco_decode_list_skill_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AdvanceStateDto? dco_decode_opt_box_autoadd_advance_state_dto(dynamic raw);

  @protected
  AdvancementChoiceDto? dco_decode_opt_box_autoadd_advancement_choice_dto(dynamic raw);

  @protected
  AdvancementOptionDto? dco_decode_opt_box_autoadd_advancement_option_dto(dynamic raw);

  @protected
  AppliedAdvanceDto? dco_decode_opt_box_autoadd_applied_advance_dto(dynamic raw);

  @protected
  RollResultDto? dco_decode_opt_box_autoadd_roll_result_dto(dynamic raw);

  @protected
  RollStateDto? dco_decode_opt_box_autoadd_roll_state_dto(dynamic raw);

  @protected
  SkillDto? dco_decode_opt_box_autoadd_skill_dto(dynamic raw);

  @protected
  SkillRefDto? dco_decode_opt_box_autoadd_skill_ref_dto(dynamic raw);

  @protected
  TieWinnerDto? dco_decode_opt_box_autoadd_tie_winner_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  RollOutcomeDto dco_decode_roll_outcome_dto(dynamic raw);

  @protected
  RollRecordDto dco_decode_roll_record_dto(dynamic raw);

  @protected
  RollResultDto dco_decode_roll_result_dto(dynamic raw);

  @protected
  RollStateDto dco_decode_roll_state_dto(dynamic raw);

  @protected
  RoomSettingsDto dco_decode_room_settings_dto(dynamic raw);

  @protected
  SkillDto dco_decode_skill_dto(dynamic raw);

  @protected
  SkillRefDto dco_decode_skill_ref_dto(dynamic raw);

  @protected
  SlotChoiceKind dco_decode_slot_choice_kind(dynamic raw);

  @protected
  SlotUsageDto dco_decode_slot_usage_dto(dynamic raw);

  @protected
  TieWinnerDto dco_decode_tie_winner_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActorDto sse_decode_actor_dto(SseDeserializer deserializer);

  @protected
  AdvanceStateDto sse_decode_advance_state_dto(SseDeserializer deserializer);

  @protected
  AdvancementChoiceDto sse_decode_advancement_choice_dto(SseDeserializer deserializer);

  @protected
  AdvancementOptionDto sse_decode_advancement_option_dto(SseDeserializer deserializer);

  @protected
  AppliedAdvanceDto sse_decode_applied_advance_dto(SseDeserializer deserializer);

  @protected
  ApplyResultDto sse_decode_apply_result_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AdvanceStateDto sse_decode_box_autoadd_advance_state_dto(SseDeserializer deserializer);

  @protected
  AdvancementChoiceDto sse_decode_box_autoadd_advancement_choice_dto(SseDeserializer deserializer);

  @protected
  AdvancementOptionDto sse_decode_box_autoadd_advancement_option_dto(SseDeserializer deserializer);

  @protected
  AppliedAdvanceDto sse_decode_box_autoadd_applied_advance_dto(SseDeserializer deserializer);

  @protected
  CharacterDto sse_decode_box_autoadd_character_dto(SseDeserializer deserializer);

  @protected
  FlowActionDto sse_decode_box_autoadd_flow_action_dto(SseDeserializer deserializer);

  @protected
  ItemDto sse_decode_box_autoadd_item_dto(SseDeserializer deserializer);

  @protected
  RollRecordDto sse_decode_box_autoadd_roll_record_dto(SseDeserializer deserializer);

  @protected
  RollResultDto sse_decode_box_autoadd_roll_result_dto(SseDeserializer deserializer);

  @protected
  RollStateDto sse_decode_box_autoadd_roll_state_dto(SseDeserializer deserializer);

  @protected
  RoomSettingsDto sse_decode_box_autoadd_room_settings_dto(SseDeserializer deserializer);

  @protected
  SkillDto sse_decode_box_autoadd_skill_dto(SseDeserializer deserializer);

  @protected
  SkillRefDto sse_decode_box_autoadd_skill_ref_dto(SseDeserializer deserializer);

  @protected
  TieWinnerDto sse_decode_box_autoadd_tie_winner_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CharacterDto sse_decode_character_dto(SseDeserializer deserializer);

  @protected
  FlowActionDto sse_decode_flow_action_dto(SseDeserializer deserializer);

  @protected
  FlowActionKindDto sse_decode_flow_action_kind_dto(SseDeserializer deserializer);

  @protected
  HistoryEntryDto sse_decode_history_entry_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ItemDto sse_decode_item_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FlowActionKindDto> sse_decode_list_flow_action_kind_dto(SseDeserializer deserializer);

  @protected
  List<HistoryEntryDto> sse_decode_list_history_entry_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SkillDto> sse_decode_list_skill_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AdvanceStateDto? sse_decode_opt_box_autoadd_advance_state_dto(SseDeserializer deserializer);

  @protected
  AdvancementChoiceDto? sse_decode_opt_box_autoadd_advancement_choice_dto(SseDeserializer deserializer);

  @protected
  AdvancementOptionDto? sse_decode_opt_box_autoadd_advancement_option_dto(SseDeserializer deserializer);

  @protected
  AppliedAdvanceDto? sse_decode_opt_box_autoadd_applied_advance_dto(SseDeserializer deserializer);

  @protected
  RollResultDto? sse_decode_opt_box_autoadd_roll_result_dto(SseDeserializer deserializer);

  @protected
  RollStateDto? sse_decode_opt_box_autoadd_roll_state_dto(SseDeserializer deserializer);

  @protected
  SkillDto? sse_decode_opt_box_autoadd_skill_dto(SseDeserializer deserializer);

  @protected
  SkillRefDto? sse_decode_opt_box_autoadd_skill_ref_dto(SseDeserializer deserializer);

  @protected
  TieWinnerDto? sse_decode_opt_box_autoadd_tie_winner_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  RollOutcomeDto sse_decode_roll_outcome_dto(SseDeserializer deserializer);

  @protected
  RollRecordDto sse_decode_roll_record_dto(SseDeserializer deserializer);

  @protected
  RollResultDto sse_decode_roll_result_dto(SseDeserializer deserializer);

  @protected
  RollStateDto sse_decode_roll_state_dto(SseDeserializer deserializer);

  @protected
  RoomSettingsDto sse_decode_room_settings_dto(SseDeserializer deserializer);

  @protected
  SkillDto sse_decode_skill_dto(SseDeserializer deserializer);

  @protected
  SkillRefDto sse_decode_skill_ref_dto(SseDeserializer deserializer);

  @protected
  SlotChoiceKind sse_decode_slot_choice_kind(SseDeserializer deserializer);

  @protected
  SlotUsageDto sse_decode_slot_usage_dto(SseDeserializer deserializer);

  @protected
  TieWinnerDto sse_decode_tie_winner_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_actor_dto(ActorDto self, SseSerializer serializer);

  @protected
  void sse_encode_advance_state_dto(AdvanceStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_advancement_choice_dto(AdvancementChoiceDto self, SseSerializer serializer);

  @protected
  void sse_encode_advancement_option_dto(AdvancementOptionDto self, SseSerializer serializer);

  @protected
  void sse_encode_applied_advance_dto(AppliedAdvanceDto self, SseSerializer serializer);

  @protected
  void sse_encode_apply_result_dto(ApplyResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_advance_state_dto(AdvanceStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_advancement_choice_dto(AdvancementChoiceDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_advancement_option_dto(AdvancementOptionDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_applied_advance_dto(AppliedAdvanceDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_character_dto(CharacterDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flow_action_dto(FlowActionDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_item_dto(ItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_roll_record_dto(RollRecordDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_roll_result_dto(RollResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_roll_state_dto(RollStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_room_settings_dto(RoomSettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_skill_dto(SkillDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_skill_ref_dto(SkillRefDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tie_winner_dto(TieWinnerDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_character_dto(CharacterDto self, SseSerializer serializer);

  @protected
  void sse_encode_flow_action_dto(FlowActionDto self, SseSerializer serializer);

  @protected
  void sse_encode_flow_action_kind_dto(FlowActionKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_history_entry_dto(HistoryEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_item_dto(ItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_flow_action_kind_dto(List<FlowActionKindDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_history_entry_dto(List<HistoryEntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_skill_dto(List<SkillDto> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_advance_state_dto(AdvanceStateDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_advancement_choice_dto(AdvancementChoiceDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_advancement_option_dto(AdvancementOptionDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_applied_advance_dto(AppliedAdvanceDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_roll_result_dto(RollResultDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_roll_state_dto(RollStateDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_skill_dto(SkillDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_skill_ref_dto(SkillRefDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_tie_winner_dto(TieWinnerDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_roll_outcome_dto(RollOutcomeDto self, SseSerializer serializer);

  @protected
  void sse_encode_roll_record_dto(RollRecordDto self, SseSerializer serializer);

  @protected
  void sse_encode_roll_result_dto(RollResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_roll_state_dto(RollStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_room_settings_dto(RoomSettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_skill_dto(SkillDto self, SseSerializer serializer);

  @protected
  void sse_encode_skill_ref_dto(SkillRefDto self, SseSerializer serializer);

  @protected
  void sse_encode_slot_choice_kind(SlotChoiceKind self, SseSerializer serializer);

  @protected
  void sse_encode_slot_usage_dto(SlotUsageDto self, SseSerializer serializer);

  @protected
  void sse_encode_tie_winner_dto(TieWinnerDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
