// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dice_roll`, `dice_source`, `engine_err`, `outcome_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Tira `count` d6 con la fuente aleatoria del proceso.
Uint8List rollDice({required int count, required int maxDice}) =>
    RustLib.instance.api.crateApiEngineRollDice(count: count, maxDice: maxDice);

RoomSettingsDto defaultRoomSettings() =>
    RustLib.instance.api.crateApiEngineDefaultRoomSettings();

/// Mensaje de error si los ajustes no son válidos.
String? validateRoomSettings({required RoomSettingsDto settings}) =>
    RustLib.instance.api.crateApiEngineValidateRoomSettings(settings: settings);

CharacterDto newCharacter({
  required String name,
  required String description,
}) => RustLib.instance.api.crateApiEngineNewCharacter(
  name: name,
  description: description,
);

/// Lista de problemas de la hoja (vacía si es válida).
List<String> validateCharacter({
  required CharacterDto character,
  required RoomSettingsDto settings,
}) => RustLib.instance.api.crateApiEngineValidateCharacter(
  character: character,
  settings: settings,
);

SlotUsageDto slotUsage({
  required CharacterDto character,
  required RoomSettingsDto settings,
}) => RustLib.instance.api.crateApiEngineSlotUsage(
  character: character,
  settings: settings,
);

String? validateItem({required ItemDto item}) =>
    RustLib.instance.api.crateApiEngineValidateItem(item: item);

RollOutcomeDto resolveRoll({
  required List<int> playerDice,
  required List<int> oppositionDice,
  required RoomSettingsDto settings,
}) => RustLib.instance.api.crateApiEngineResolveRoll(
  playerDice: playerDice,
  oppositionDice: oppositionDice,
  settings: settings,
);

/// Avance posible tras una tirada (o `None` si no hay).
AdvancementOptionDto? advancementOption({
  required CharacterDto character,
  required RoomSettingsDto settings,
  required List<int> playerDice,
  required List<int> oppositionDice,
  required int skillIndex,
}) => RustLib.instance.api.crateApiEngineAdvancementOption(
  character: character,
  settings: settings,
  playerDice: playerDice,
  oppositionDice: oppositionDice,
  skillIndex: skillIndex,
);

/// Aplica el resultado a la hoja: XP por fallo y la habilidad elegida.
ApplyResultDto applyRoll({
  required CharacterDto character,
  required RoomSettingsDto settings,
  required List<int> playerDice,
  required List<int> oppositionDice,
  required int skillIndex,
  AdvancementChoiceDto? choice,
}) => RustLib.instance.api.crateApiEngineApplyRoll(
  character: character,
  settings: settings,
  playerDice: playerDice,
  oppositionDice: oppositionDice,
  skillIndex: skillIndex,
  choice: choice,
);

class AdvancementChoiceDto {
  final String newSkillName;
  final SlotChoiceKind slot;

  /// Solo con `Replace`.
  final int replaceIndex;

  const AdvancementChoiceDto({
    required this.newSkillName,
    required this.slot,
    required this.replaceIndex,
  });

  @override
  int get hashCode =>
      newSkillName.hashCode ^ slot.hashCode ^ replaceIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdvancementChoiceDto &&
          runtimeType == other.runtimeType &&
          newSkillName == other.newSkillName &&
          slot == other.slot &&
          replaceIndex == other.replaceIndex;
}

class AdvancementOptionDto {
  final int sourceSkillIndex;
  final String sourceLabel;
  final int newLevel;
  final bool natural;
  final int xpCost;
  final int xpAvailable;
  final bool slotsFull;

  const AdvancementOptionDto({
    required this.sourceSkillIndex,
    required this.sourceLabel,
    required this.newLevel,
    required this.natural,
    required this.xpCost,
    required this.xpAvailable,
    required this.slotsFull,
  });

  @override
  int get hashCode =>
      sourceSkillIndex.hashCode ^
      sourceLabel.hashCode ^
      newLevel.hashCode ^
      natural.hashCode ^
      xpCost.hashCode ^
      xpAvailable.hashCode ^
      slotsFull.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdvancementOptionDto &&
          runtimeType == other.runtimeType &&
          sourceSkillIndex == other.sourceSkillIndex &&
          sourceLabel == other.sourceLabel &&
          newLevel == other.newLevel &&
          natural == other.natural &&
          xpCost == other.xpCost &&
          xpAvailable == other.xpAvailable &&
          slotsFull == other.slotsFull;
}

class ApplyResultDto {
  final CharacterDto character;
  final int xpGained;
  final int xpSpent;
  final SkillDto? newSkill;
  final int? replacedIndex;
  final SkillDto? replacedSkill;

  const ApplyResultDto({
    required this.character,
    required this.xpGained,
    required this.xpSpent,
    this.newSkill,
    this.replacedIndex,
    this.replacedSkill,
  });

  @override
  int get hashCode =>
      character.hashCode ^
      xpGained.hashCode ^
      xpSpent.hashCode ^
      newSkill.hashCode ^
      replacedIndex.hashCode ^
      replacedSkill.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyResultDto &&
          runtimeType == other.runtimeType &&
          character == other.character &&
          xpGained == other.xpGained &&
          xpSpent == other.xpSpent &&
          newSkill == other.newSkill &&
          replacedIndex == other.replacedIndex &&
          replacedSkill == other.replacedSkill;
}

class CharacterDto {
  final String name;
  final String description;
  final String notes;
  final int xp;
  final List<SkillDto> skills;

  const CharacterDto({
    required this.name,
    required this.description,
    required this.notes,
    required this.xp,
    required this.skills,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      notes.hashCode ^
      xp.hashCode ^
      skills.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharacterDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          notes == other.notes &&
          xp == other.xp &&
          skills == other.skills;
}

class ItemDto {
  final String name;
  final String description;
  final int? value;
  final int quantity;

  const ItemDto({
    required this.name,
    required this.description,
    this.value,
    required this.quantity,
  });

  @override
  int get hashCode =>
      name.hashCode ^ description.hashCode ^ value.hashCode ^ quantity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ItemDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          value == other.value &&
          quantity == other.quantity;
}

class RollOutcomeDto {
  final bool success;
  final int playerTotal;
  final int oppositionTotal;
  final int xpGained;

  const RollOutcomeDto({
    required this.success,
    required this.playerTotal,
    required this.oppositionTotal,
    required this.xpGained,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      playerTotal.hashCode ^
      oppositionTotal.hashCode ^
      xpGained.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RollOutcomeDto &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          playerTotal == other.playerTotal &&
          oppositionTotal == other.oppositionTotal &&
          xpGained == other.xpGained;
}

class RoomSettingsDto {
  final int skillSlots;
  final TieWinnerDto tieWinner;
  final bool xpSameRoll;
  final int maxDice;

  const RoomSettingsDto({
    required this.skillSlots,
    required this.tieWinner,
    required this.xpSameRoll,
    required this.maxDice,
  });

  @override
  int get hashCode =>
      skillSlots.hashCode ^
      tieWinner.hashCode ^
      xpSameRoll.hashCode ^
      maxDice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSettingsDto &&
          runtimeType == other.runtimeType &&
          skillSlots == other.skillSlots &&
          tieWinner == other.tieWinner &&
          xpSameRoll == other.xpSameRoll &&
          maxDice == other.maxDice;
}

class SkillDto {
  final String name;
  final int level;
  final bool permanent;
  final String? derivedFrom;

  const SkillDto({
    required this.name,
    required this.level,
    required this.permanent,
    this.derivedFrom,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      level.hashCode ^
      permanent.hashCode ^
      derivedFrom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          level == other.level &&
          permanent == other.permanent &&
          derivedFrom == other.derivedFrom;
}

enum SlotChoiceKind { append, replace, discard }

class SlotUsageDto {
  final int used;
  final int capacity;

  const SlotUsageDto({required this.used, required this.capacity});

  @override
  int get hashCode => used.hashCode ^ capacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlotUsageDto &&
          runtimeType == other.runtimeType &&
          used == other.used &&
          capacity == other.capacity;
}

enum TieWinnerDto { player, opposition }
