// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'engine.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `action_to_engine`, `missing`, `record_from_engine`, `record_to_engine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Nueva tirada en estado `declarada`.
RollRecordDto declareRoll({required String action, required SkillRefDto skill}) =>
    RustLib.instance.api.crateApiFlowDeclareRoll(action: action, skill: skill);

/// Aplica una acción y devuelve la tirada resultante.
RollRecordDto rollTransition({
  required RollRecordDto record,
  required FlowActionDto action,
  required ActorDto actor,
  required int maxDice,
}) => RustLib.instance.api.crateApiFlowRollTransition(record: record, action: action, actor: actor, maxDice: maxDice);

/// Acciones disponibles para `actor` en el estado actual de la tirada.
List<FlowActionKindDto> allowedRollActions({
  required RollStateDto state,
  AdvanceStateDto? advance,
  required ActorDto actor,
}) => RustLib.instance.api.crateApiFlowAllowedRollActions(state: state, advance: advance, actor: actor);

/// Identificador del estado tal como se guarda en Firestore.
String rollStateId({required RollStateDto state}) => RustLib.instance.api.crateApiFlowRollStateId(state: state);

RollStateDto? parseRollState({required String id}) => RustLib.instance.api.crateApiFlowParseRollState(id: id);

enum ActorDto { dm, owner, other }

enum AdvanceStateDto { pendiente, aplicado, noAplica }

class AppliedAdvanceDto {
  final int xpGained;
  final int xpSpent;
  final SkillDto? newSkill;
  final int? replacedIndex;

  const AppliedAdvanceDto({required this.xpGained, required this.xpSpent, this.newSkill, this.replacedIndex});

  @override
  int get hashCode => xpGained.hashCode ^ xpSpent.hashCode ^ newSkill.hashCode ^ replacedIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppliedAdvanceDto &&
          runtimeType == other.runtimeType &&
          xpGained == other.xpGained &&
          xpSpent == other.xpSpent &&
          newSkill == other.newSkill &&
          replacedIndex == other.replacedIndex;
}

/// Acción del flujo. Solo se usan los campos que correspondan a `kind`:
/// - `CounterOffer`: `skill`, `text` (nota)
/// - `Reject`: `text` (nota)
/// - `Narrate`: `text` (narración)
/// - `Redeclare`: `text` (acción), `skill`
/// - `RollOpposition` / `RollPlayer`: `dice`
/// - `Resolve`: `tie_winner`
/// - `ApplyAdvance`: `applied`
class FlowActionDto {
  final FlowActionKindDto kind;
  final SkillRefDto? skill;
  final String? text;
  final Uint8List? dice;
  final TieWinnerDto? tieWinner;
  final AppliedAdvanceDto? applied;

  const FlowActionDto({required this.kind, this.skill, this.text, this.dice, this.tieWinner, this.applied});

  @override
  int get hashCode =>
      kind.hashCode ^ skill.hashCode ^ text.hashCode ^ dice.hashCode ^ tieWinner.hashCode ^ applied.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlowActionDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          skill == other.skill &&
          text == other.text &&
          dice == other.dice &&
          tieWinner == other.tieWinner &&
          applied == other.applied;
}

enum FlowActionKindDto {
  approve,
  counterOffer,
  reject,
  narrate,
  acceptCounterOffer,
  redeclare,
  withdraw,
  rollOpposition,
  rollPlayer,
  resolve,
  applyAdvance,
}

class HistoryEntryDto {
  final RollStateDto? from;
  final RollStateDto to;
  final ActorDto by;

  const HistoryEntryDto({this.from, required this.to, required this.by});

  @override
  int get hashCode => from.hashCode ^ to.hashCode ^ by.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryEntryDto &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          by == other.by;
}

class RollRecordDto {
  final RollStateDto state;
  final String action;
  final SkillRefDto skill;
  final SkillRefDto? counterOffer;
  final String? dmNote;
  final Uint8List? opposition;
  final Uint8List? playerRoll;
  final RollResultDto? result;
  final String? narration;
  final TieWinnerDto? tieWinner;
  final AdvanceStateDto? advance;
  final AppliedAdvanceDto? applied;
  final List<HistoryEntryDto> history;

  const RollRecordDto({
    required this.state,
    required this.action,
    required this.skill,
    this.counterOffer,
    this.dmNote,
    this.opposition,
    this.playerRoll,
    this.result,
    this.narration,
    this.tieWinner,
    this.advance,
    this.applied,
    required this.history,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      action.hashCode ^
      skill.hashCode ^
      counterOffer.hashCode ^
      dmNote.hashCode ^
      opposition.hashCode ^
      playerRoll.hashCode ^
      result.hashCode ^
      narration.hashCode ^
      tieWinner.hashCode ^
      advance.hashCode ^
      applied.hashCode ^
      history.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RollRecordDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          action == other.action &&
          skill == other.skill &&
          counterOffer == other.counterOffer &&
          dmNote == other.dmNote &&
          opposition == other.opposition &&
          playerRoll == other.playerRoll &&
          result == other.result &&
          narration == other.narration &&
          tieWinner == other.tieWinner &&
          advance == other.advance &&
          applied == other.applied &&
          history == other.history;
}

enum RollResultDto { exito, fallo, narrado }

enum RollStateDto { declarada, aprobada, contraoferta, rechazada, sinTirada, oposicion, tirada, resuelta, retirada }

class SkillRefDto {
  final int index;
  final String name;
  final int level;

  const SkillRefDto({required this.index, required this.name, required this.level});

  @override
  int get hashCode => index.hashCode ^ name.hashCode ^ level.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillRefDto &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          level == other.level;
}
