// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Reserva la primera plaza libre (0, 1, 2…) con un mutex con nombre de Windows.
/// El sistema la libera al cerrarse el proceso, aunque sea por un fallo.
/// Devuelve `None` si todas están ocupadas.
int? acquireInstanceSlot({required int maxSlots}) =>
    RustLib.instance.api.crateApiInstanceAcquireInstanceSlot(maxSlots: maxSlots);
